
USE EMPLOYEE;
SHOW DATABASES;
CREATE TABLE EMPLOYEE_DETAILS(
EMP_ID VARCHAR(18),
EMP_NAME VARCHAR(20),
EMP_DESIGNATION VARCHAR(20),
EMP_AGE INT(20));
desc  EMPLOYEE_DETAILS;
INSERT INTO EMPLOYEE_DETAILS VALUES
('ES3456','LAVANYA','HR',24),
('ES3457','GAYTHRI','HR',28),
('ES3458','GOHUL','HR',25),
('ES3459','PREETHA','HR',24),
('ES3460','SHAHANA','HR',20);
SELECT * FROM EMPLOYEE_DETAILS;


