
USE EMPLOYEE;
SHOW DATABASES;
CREATE TABLE EMPLOYEE_DETAILS(
EMP_ID VARCHAR(18),
EMP_NAME VARCHAR(20),
EMP_DESIGNATION VARCHAR(20),
EMP_AGE INT(20));
desc  EMPLOYEE_DETAILS;
INSERT INTO EMPLOYEE_DETAILS VALUES
('ES3456','LAVANYA','HR',36),
('ES3457','LAVANYA','HR',28),
('ES3458','LAVANYA','HR',25),
('ES3459','LAVANYA','HR',24),
('ES3460','LAVANYA','HR',20);

SELECT * FROM EMPLOYEE_DETAILS;
SELECT EMP_ID,EMP_AGE FROM EMPLOYEE_DETAILS;

